# Antes estava /junior, agora você aponta para o novo nome
spring.datasource.url=jdbc:postgresql://localhost:5456/biblioteca_projeto
# Mantenha o usuário e senha que você definiu no seu docker-compose
spring.datasource.username=junior
spring.datasource.password=junior

# Hibernate vai criar as tabelas no Docker pra você
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect